title: ServoDevelop Wiki
remote_theme: just-the-docs/just-the-docs
color_scheme: dark

# 确保这里的路径与你的仓库名一致
url: "https://servodevelop.github.io"
baseurl: "/wiki"

# 加载自定义脚本
head_custom: _includes/head_custom.html
