site_name: Fashion Star Wiki
site_url: https://servodevelop.github.io/wiki/

theme:
  name: material
  language: zh
  features:
    - navigation.tabs             # 开启顶部一级导航（如不需要可删除）
    - navigation.expand           # 默认展开/折叠功能
    - navigation.indexes          # 允许点击父级目录标题跳转
    - navigation.top              # 回到顶部按钮
    - content.code.copy           # 代码一键复制
    - toc.follow                  # 右侧目录跟随滚动
  
  # 颜色方案配置：保留黑白切换逻辑
  palette:
    # 浅色模式
    - scheme: default
      primary: custom             # 品牌色 #8641A9
      accent: custom
      toggle:
        icon: material/brightness-7
        name: 切换至深色模式
    # 深色模式
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: 切换至浅色模式

plugins:
  - search
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      zoomable: true
      draggable: true

markdown_extensions:
  - pymdownx.snippets:
      base_path: ["docs"]
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - UART Servo:
      - Datasheet:
          - HA8/RA8-U25(H)-M: uart_servo/datasheet/HA_RA8_U25(H)_M.md
          - HA8/RA8-U35(H)-M: uart_servo/datasheet/HA_RA8_U35(H)_M.md
      - CAD Files:
          - STEP/DWG/PDF: uart_servo/cad_files/cad_files.md
      - Software: 
          - Configuration Tools: uart_servo/software/pc_configuration_ser_manual.md
  - Robotic Arm:
      - StarAI Arm: 
          - Quick Start: robotic_arm/starai_arm/index.md
      - Piper Mate: 
          - User Manual: robotic_arm/piper_mate/index.md
