plugins:
  - search
  - glightbox
  - include-markdown:
      rewrite_relative_urls: true
      dedent: true
  - i18n:
      default_locale: en
      reconfigure_material: true
      fallback_to_default: true 
      languages:
        - locale: en
          name: "English"  # 暂时去掉 emoji，排除特殊字符干扰
          default: true
          build: true
        - locale: zh
          name: "中文"     # 暂时去掉 emoji
          default: false
          build: true
      # 调试：给所有 Key 加上双引号，并增加最简单的测试项
      nav_translations:
        zh:
          "Home": "首页"
          "Uart Bus Servo": "串口总线舵机"
          "RS485 Bus Servo": "RS485总线舵机"
          "CAN Bus Servo": "CAN总线舵机"
          "Protocol": "通讯协议"
          "Specifications": "规格参数"
          "CAD Files": "CAD文件"
          "Software": "配套软件"
          "SDK": "开发库"
          "PLC": "工业PLC"
          "Document": "官方文档"
          "Robotic Arm": "机械臂"
          "StarAI Arm": "StarAI机械臂"
          "Piper Mate": "Piper Mate机械臂"
          "Quick Start": "快速入门"
          "Get Ready": "准备工作"

nav:
  - "Home": index.md
  - "Uart Bus Servo":
    - uart_servo/index.md
    - "Protocol": uart_servo/protocols/uart_rs485_protocol.md
    - "Specifications":
      - RP6-U12H-M: uart_servo/specs/rp6-u12h-m.md
      # ...
